import type { Metadata } from "next";
import Image from "next/image";
import LocaleButton from "@/components/locale-button";

import MainImage from "@/assets/images/main-mid.png";
import "../css/index.css";
import MobileHeader from "@/components/layout/mobile-header";
import MobileFooter from "@/components/layout/mobile-footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={"font-pretendard"}>
        <div className="absolute z-50">
          <LocaleButton />
        </div>
        <div className="max-h-screen bg-SYSTEM-main overflow-hidden">
          <div className="relative px-0 sm:px-6 md:px-10">
            <div className="flex justify-center lg:justify-around">
              <div className=" hidden lg:flex flex-col">
                <Image src={MainImage} alt="nito-main" width={400} />
              </div>
              <div className="grid grid-rows-[44px_auto_30px] w-full max-w-[375px] h-screen bg-SYSTEM-white">
                <div className="sticky z-40 w-full">
                  <MobileHeader />
                </div>
                <div className="relative p-4">{children}</div>
                <div className="z-40 bg-SYSTEM-white">
                  <MobileFooter />
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
